/*
 * Copyright (C) 2016 August Enzelberger <augustenz+github@gmail.com> (https://github.com/augustenz)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package sttcollectionmanager;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 *
 * August Enzelberger <augustenz+github@gmail.com> (https://github.com/augustenz)
 */
public class HTMLExporter {
    public void exportTable(JTable table, File file, String tableName) throws IOException {
        TableModel model = table.getModel();
        FileWriter out = new FileWriter(file);
        
        int columns=model.getColumnCount()-1;
        
        //if(tableName.equals("STT Crew Collection"))
        //    columns-=1;
            
        String HTML="<html>\n";
        HTML+="\t<head>\n";
        HTML+="\t\t<title>"+tableName+" "+" - Generated by STT Collection Manager</title>";
        HTML+="\n\t</head>\n";
        HTML+="\t<BODY>\n";
        HTML+="\t\t<font face=\"Arial\">\n";
        HTML+="\t\t\t<h1>"+tableName+"</h1>\n";
        HTML+="\t\t\t<table border=\"1\" cellpadding=\"2\" cellspacing=\"0\">\n";

        HTML+="\t\t\t<tr>\n";
        for(int i=0; i<columns; i++) {
            HTML+="\t\t\t\t<th>"+model.getColumnName(i)+"</th>\n";
        }
        HTML+="\t\t\t</tr>\n";


        for(int i=0; i<model.getRowCount(); i++) {
            HTML+="\t\t\t<tr>\n";       
            for(int j=0; j < columns; j++) {
                try {
                    if(!tableName.equals("STT Crew Collection"))
                        if(model.getValueAt(i,12).toString().equals("true"))
                            HTML+="\t\t\t\t<td><b>"+model.getValueAt(i,j).toString()+"</b></td>\n";
                        else
                            HTML+="\t\t\t\t<td>"+model.getValueAt(i,j).toString()+"</td>\n";
                }
                catch (NullPointerException ex) {
                    System.out.println("Cell("+i+":"+j+")=null");
                }
            }
            HTML+="\t\t\t</tr>\n";
        }

        HTML+="\t\t\t</table>\n";
        HTML+="\t\t</font>\n";
        HTML+="\t</BODY>\n";
        HTML+="</HTML>\n";

        out.write(HTML);
        out.close();
        System.out.println("write out to: " + file);
    }
}
