/*
 * Copyright (C) 2017 August Enzelberger <augustenz+github@gmail.com> (https://github.com/augustenz)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package sttcollectionmanager;

/**
 *
 * @author August Enzelberger <augustenz+github@gmail.com>
 * (https://github.com/augustenz)
 */
public class ProgressJPanel extends javax.swing.JPanel {

    /**
     * Creates new form progressJPanel
     */
    public ProgressJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        progressScrollPane = new javax.swing.JScrollPane();
        progressTextArea = new javax.swing.JTextArea();
        progressProgressBar = new javax.swing.JProgressBar();

        setLayout(new java.awt.GridBagLayout());

        progressTextArea.setColumns(20);
        progressTextArea.setRows(5);
        progressScrollPane.setViewportView(progressTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 377;
        gridBagConstraints.ipady = 277;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(progressScrollPane, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(progressProgressBar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar progressProgressBar;
    private javax.swing.JScrollPane progressScrollPane;
    private javax.swing.JTextArea progressTextArea;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the progressScrollPane
     */
    public javax.swing.JScrollPane getProgressScrollPane() {
        return progressScrollPane;
    }

    /**
     * @param progressScrollPane the progressScrollPane to set
     */
    public void setProgressScrollPane(javax.swing.JScrollPane progressScrollPane) {
        this.progressScrollPane = progressScrollPane;
    }

    /**
     * @return the progressTextArea
     */
    public javax.swing.JTextArea getProgressTextArea() {
        return progressTextArea;
    }

    /**
     * @param progressTextArea the progressTextArea to set
     */
    public void setProgressTextArea(javax.swing.JTextArea progressTextArea) {
        this.progressTextArea = progressTextArea;
    }

    /**
     * @return the progressProgressBar
     */
    public javax.swing.JProgressBar getProgressProgressBar() {
        return progressProgressBar;
    }

    /**
     * @param progressProgressBar the progressProgressBar to set
     */
    public void setProgressProgressBar(javax.swing.JProgressBar progressProgressBar) {
        this.progressProgressBar = progressProgressBar;
    }
}
